# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Abhishek@4987
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Day 30: Google OAuth2 Login ("Sign in with Google")
# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=511263262757-pgj71pq83ug9920itknbdb87i2f3c09j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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